version: '3'

services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:6.6.1
    restart: unless-stopped
    volumes:
      - rocketchat-uploads:/app/uploads
    environment:
      MONGO_URL: mongodb://mongodb:27017/rocketchat?replicaSet=rs0
      MONGO_OPLOG_URL: mongodb://mongodb:27017/local?replicaSet=rs0
      ROOT_URL: https:/192.168.0.8:3000   # Reemplaza example.com con tu dominio
      PORT: 3000
      DEPLOY_METHOD: docker
      Accounts_UseDNSDomainCheck: 'false'
    depends_on:
      - mongodb

  mongodb:
    image: bitnami/mongodb:6.0
    restart: unless-stopped
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_HOST: mongodb
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      MONGODB_ENABLE_JOURNAL: 'true'
      ALLOW_EMPTY_PASSWORD: 'yes'

  portainer:
    image: portainer/portainer-ce
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - /ruta/a/tu/certificado.crt:/etc/nginx/cert.crt
      - /ruta/a/tu/clave_privada.key:/etc/nginx/cert.key
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
